//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoweredSoft.DbUtils.Schema.MySql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySqlSchemaQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySqlSchemaQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoweredSoft.DbUtils.Schema.MySql.MySqlSchemaQueries", typeof(MySqlSchemaQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	TABLE_NAME,
        ///    IS_NULLABLE,
        ///    DATA_TYPE,
        ///    COLUMN_NAME,
        ///    COLUMN_DEFAULT,
        ///   COLUMN_TYPE, CHARACTER_MAXIMUM_LENGTH,
        ///    NUMERIC_PRECISION,
        ///    NUMERIC_SCALE,
        ///    DATETIME_PRECISION,
        ///    IF (EXTRA = &apos;auto_increment&apos;, TRUE, FALSE) As IS_AUTO_INCREMENT
        ///    
        ///FROM INFORMATION_SCHEMA.COLUMNS  
        ///WHERE TABLE_SCHEMA = @DatabaseName ORDER BY TABLE_NAME.
        /// </summary>
        internal static string FetchColumns {
            get {
                return ResourceManager.GetString("FetchColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	TC.CONSTRAINT_NAME AS FKName,
        ///    TC.TABLE_NAME AS FKTable,
        ///    KCU.COLUMN_NAME AS FKColumn,
        ///    KCU.REFERENCED_TABLE_NAME AS PKTable,
        ///    KCU.REFERENCED_COLUMN_NAME AS PKColumn,
        ///    RC.UPDATE_RULE AS UpdateCascadeAction,
        ///    RC.DELETE_RULE AS DeleteCascadeAction
        ///from 
        ///	INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
        ///INNER JOIN
        ///	INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
        ///ON
        ///	TC.CONSTRAINT_SCHEMA = KCU.TABLE_SCHEMA
        ///    AND
        ///    TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
        ///INNER JOIN
        ///	INFORMATION_SCHEMA.REFERENTIAL_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FetchForeignKeys {
            get {
                return ResourceManager.GetString("FetchForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	S.INDEX_NAME As IndexName,
        ///    S.TABLE_NAME As TableName,
        ///    S.COLUMN_NAME As ColumnName,
        ///    SEQ_IN_INDEX AS KeyOrdinal,
        ///    IF (NON_UNIQUE, FALSE, TRUE) As IsUniqueConstraint
        ///FROM 
        ///	INFORMATION_SCHEMA.STATISTICS S
        ///WHERE
        ///	S.TABLE_SCHEMA = &apos;Acme&apos;
        ///;
        ///
        ///SELECT
        ///	*
        ///FROM 
        ///	INFORMATION_SCHEMA.STATISTICS S
        ///WHERE
        ///	S.TABLE_SCHEMA = @DatabaseName;.
        /// </summary>
        internal static string FetchIndexes {
            get {
                return ResourceManager.GetString("FetchIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	T.TABLE_NAME,
        ///    KCU.COLUMN_NAME,
        ///    KCU.ORDINAL_POSITION
        ///FROM 
        ///	INFORMATION_SCHEMA.TABLE_CONSTRAINTS T
        ///INNER JOIN
        ///	INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
        ///ON
        ///	KCU.CONSTRAINT_SCHEMA = KCU.TABLE_SCHEMA AND KCU.TABLE_NAME = T.TABLE_NAME AND KCU.CONSTRAINT_NAME = T.CONSTRAINT_NAME
        ///WHERE 
        ///	T.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos; AND T.CONSTRAINT_SCHEMA = @DatabaseName ORDER BY 
        ///	T.TABLE_NAME, KCU.ORDINAL_POSITION.
        /// </summary>
        internal static string FetchPrimaryKeys {
            get {
                return ResourceManager.GetString("FetchPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_TYPE = &apos;BASE TABLE&apos; AND T.TABLE_SCHEMA = @DatabaseName ORDER BY T.TABLE_NAME;.
        /// </summary>
        internal static string FetchTables {
            get {
                return ResourceManager.GetString("FetchTables", resourceCulture);
            }
        }
    }
}
